# Generated by Django 6.0.3 on 2026-04-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='yearly_paid_leaves',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='leave',
            name='month',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('total_leaves', models.IntegerField(default=0)),
                ('paid_leaves', models.IntegerField(default=0)),
                ('unpaid_leaves', models.IntegerField(default=0)),
                ('cut_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='salary.employee')),
            ],
        ),
    ]
