# Generated by Django 6.0.3 on 2026-04-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='comp_off_leaves',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
